version: "3"

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:8.3.0
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml
      - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  otel-collector:
    container_name: otel-collector
    image: otel/opentelemetry-collector:0.41.0
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "55679:55679" # for zPages
    volumes:
      - ./grafana/otel-collector.yml:/etc/otel-collector/config.yml
    command:
      - --config=/etc/otel-collector/config.yml
    networks:
      - default
      - shared-network

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    ports:
      - "3200" # tempo
      - "55680" # otlp grpc
      - "55681" # otlp http
    volumes:
      - ./grafana/tempo.yml:/etc/tempo.yml
      - ./grafana/data/tempo:/tmp/tempo
    command:
      - "-config.file=/etc/tempo.yml"

  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    logging:
      driver: loki
      options:
        loki-url: 'http://localhost:3100/loki/api/v1/push'

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.31.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.grafana.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    networks:
      - default
      - shared-network

networks:
  shared-network:
    external: true
