version: '3'
services:
  terraform:
    container_name: terraform
    image: hashicorp/terraform:1.1.6
    env_file:
      - .env
    volumes:
      - .:/terraform
    working_dir: /terraform
    entrypoint: ash
    tty: true
