global:
  scrape_interval:     3s 
  evaluation_interval: 3s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - 'localhost:9090'
  - job_name: 'app'
    static_configs:
      - targets: 
        - 'app:8888'
